## Problem Set 4
### MACS 30100, Dr. Evans
### Leoson Hoay

**Importing necessary packages:**

In [29]:
import numpy as np
import pandas as pd
from pandas.plotting import scatter_matrix
import sklearn as sk
from sklearn import neighbors
from sklearn.cross_validation import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report
import math
import statsmodels.api as sm
import scipy.stats
import matplotlib.pyplot as plt

### Problem (1) 
**Multiple Linear Regression**

**(a)**

In [2]:
# identifying NA values as '?'
auto_df = pd.read_csv("../../../ProblemSets/PS4/Auto.csv", na_values = "?")

In [3]:
auto_df.head(50)

mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0   18.0          8         307.0       130.0    3504          12.0    70   
1   15.0          8         350.0       165.0    3693          11.5    70   
2   18.0          8         318.0       150.0    3436          11.0    70   
3   16.0          8         304.0       150.0    3433          12.0    70   
4   17.0          8         302.0       140.0    3449          10.5    70   
5   15.0          8         429.0       198.0    4341          10.0    70   
6   14.0          8         454.0       220.0    4354           9.0    70   
7   14.0          8         440.0       215.0    4312           8.5    70   
8   14.0          8         455.0       225.0    4425          10.0    70   
9   15.0          8         390.0       190.0    3850           8.5    70   
10  15.0          8         383.0       170.0    3563          10.0    70   
11  14.0          8         340.0       160.0    3609           8.0    70   
12  15.0          8         400.0       150.0    3761           9.5    70   
13  14.0          8         455.0       225.0    3086          10.0    70   
14  24.0          4         113.0        95.0    2372          15.0    70   
15  22.0          6         198.0        95.0    2833          15.5    70   
16  18.0          6         199.0        97.0    2774          15.5    70   
17  21.0          6         200.0        85.0    2587          16.0    70   
18  27.0          4          97.0        88.0    2130          14.5    70   
19  26.0          4          97.0        46.0    1835          20.5    70   
20  25.0          4         110.0        87.0    2672          17.5    70   
21  24.0          4         107.0        90.0    2430          14.5    70   
22  25.0          4         104.0        95.0    2375          17.5    70   
23  26.0          4         121.0       113.0    2234          12.5    70   
24  21.0          6         199.0        90.0    2648          15.0    70   
25  10.0          8         360.0       215.0    4615          14.0    70   
26  10.0          8         307.0       200.0    4376          15.0    70   
27  11.0          8         318.0       210.0    4382          13.5    70   
28   9.0          8         304.0       193.0    4732          18.5    70   
29  27.0          4          97.0        88.0    2130          14.5    71   
30  28.0          4         140.0        90.0    2264          15.5    71   
31  25.0          4         113.0        95.0    2228          14.0    71   
32  25.0          4          98.0         NaN    2046          19.0    71   
33  19.0          6         232.0       100.0    2634          13.0    71   
34  16.0          6         225.0       105.0    3439          15.5    71   
35  17.0          6         250.0       100.0    3329          15.5    71   
36  19.0          6         250.0        88.0    3302          15.5    71   
37  18.0          6         232.0       100.0    3288          15.5    71   
38  14.0          8         350.0       165.0    4209          12.0    71   
39  14.0          8         400.0       175.0    4464          11.5    71   
40  14.0          8         351.0       153.0    4154          13.5    71   
41  14.0          8         318.0       150.0    4096          13.0    71   
42  12.0          8         383.0       180.0    4955          11.5    71   
43  13.0          8         400.0       170.0    4746          12.0    71   
44  13.0          8         400.0       175.0    5140          12.0    71   
45  18.0          6         258.0       110.0    2962          13.5    71   
46  22.0          4         140.0        72.0    2408          19.0    71   
47  19.0          6         250.0       100.0    3282          15.0    71   
48  18.0          6         250.0        88.0    3139          14.5    71   
49  23.0          4         122.0        86.0    2220          14.0    71   

    origin                          name  
0        1     chevrolet chevelle 

**(b)**

In [4]:
%matplotlib notebook
axs = scatter_matrix(auto_df, alpha=0.3, figsize =(6,6), diagonal='kde')
# rotate labels for visibility
n = len(auto_df.columns)
for x in range(n-1):
    for y in range(n-1):
        ax = axs[x, y]  
        ax.xaxis.label.set_rotation(15) 
        ax.yaxis.label.set_rotation(75)
        ax.yaxis.labelpad = 25

<IPython.core.display.Javascript object>

**(c)**

In [5]:
auto_df.corr('pearson', 1)

mpg  cylinders  displacement  horsepower    weight  \
mpg           1.000000  -0.776260     -0.804443   -0.778427 -0.831739   
cylinders    -0.776260   1.000000      0.950920    0.842983  0.897017   
displacement -0.804443   0.950920      1.000000    0.897257  0.933104   
horsepower   -0.778427   0.842983      0.897257    1.000000  0.864538   
weight       -0.831739   0.897017      0.933104    0.864538  1.000000   
acceleration  0.422297  -0.504061     -0.544162   -0.689196 -0.419502   
year          0.581469  -0.346717     -0.369804   -0.416361 -0.307900   
origin        0.563698  -0.564972     -0.610664   -0.455171 -0.581265   

              acceleration      year    origin  
mpg               0.422297  0.581469  0.563698  
cylinders        -0.504061 -0.346717 -0.564972  
displacement     -0.544162 -0.369804 -0.610664  
horsepower       -0.689196 -0.416361 -0.455171  
weight           -0.419502 -0.307900 -0.581265  
acceleration      1.000000  0.282901  0.210084  
year              0.282901  1.000000  0.184314  
origin            0.210084  0.184314  1.000000

**(d)**

In [6]:
# adding intercept term
auto_df['const'] = 1

In [7]:
reg1 = sm.OLS(auto_df['mpg'], auto_df[['const', 'cylinders', 'displacement', 'horsepower', 'weight', 
                                       'acceleration', 'year', 'origin']], missing='drop')

In [8]:
results1 = reg1.fit()

In [9]:
print(results1.summary())

                            OLS Regression Results                            
Dep. Variable:                    mpg   R-squared:                       0.821
Model:                            OLS   Adj. R-squared:                  0.818
Method:                 Least Squares   F-statistic:                     252.4
Date:                Fri, 02 Feb 2018   Prob (F-statistic):          2.04e-139
Time:                        00:47:11   Log-Likelihood:                -1023.5
No. Observations:                 392   AIC:                             2063.
Df Residuals:                     384   BIC:                             2095.
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const          -17.2184      4.644     -3.707   

**(i)**

**$\beta_2$ (displacement), $\beta_4$ (weight), $\beta_6$ (year), and $\beta_7$ (origin)** are statistically significant at the 1% level. 

**(ii)**

**$\beta_1$ (cylinders), $\beta_3$ (horsepower), and $\beta_5$ (acceleration)** are not statistically significant at the 10% level.

**(iii)**

A **single unit change in the year variable (1 year)** results in a corresponding **~0.75 unit change in mpg (miles per gallon)**, all else kept constant.

**(e)**

From the scatterplot, it seems that **acceleration, horsepower, and displacement** are likely to have a non-linear relationship with mpg.

**(i)**

In [10]:
auto_df['displacement_squared'] = auto_df['displacement'].apply(lambda x: x**2)
auto_df['horsepower_squared'] = auto_df['horsepower'].apply(lambda x: x**2)
auto_df['acceleration_squared'] = auto_df['acceleration'].apply(lambda x: x**2)

In [11]:
reg2 = sm.OLS(auto_df['mpg'], auto_df[['const', 'cylinders', 'displacement', 'horsepower', 'weight', 
                                       'acceleration', 'year', 'origin', 'displacement_squared', 
                                       'horsepower_squared', 'acceleration_squared']], missing='drop')

In [12]:
results2 = reg2.fit()

In [13]:
print(results2.summary())

                            OLS Regression Results                            
Dep. Variable:                    mpg   R-squared:                       0.864
Model:                            OLS   Adj. R-squared:                  0.860
Method:                 Least Squares   F-statistic:                     241.5
Date:                Fri, 02 Feb 2018   Prob (F-statistic):          4.05e-158
Time:                        00:47:11   Log-Likelihood:                -970.53
No. Observations:                 392   AIC:                             1963.
Df Residuals:                     381   BIC:                             2007.
Df Model:                          10                                         
Covariance Type:            nonrobust                                         
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
const                    6.9847 

**(ii)**

The adjusted R-squared in (e) is **0.860**, which is **greater than the original statistic of 0.818 in part (d)**.

**(iii)**

The displacement term became **statistically significant at the 0.1% level (p-value < 0.01)**, while its coefficient changed from positive (0.0199) to negative (-0.0700). The significance of its squared term is also **statistically significant (p-value < 0.01)**.

**(iv)**

The cylinders term became **statistically significant at the 5% level (from p-value = 0.128 to p-value = 0.018)**.

**(f)**

In [14]:
results2.predict(exog=[1, 6, 200, 100, 3100, 15.1, 99, 1, 200**2, 100**2, 15.1**2])

array([38.49803518])

The predicted mpg of this particular vehicle would be **approximately 38.50 miles**.

### Problem (2) 
**Classification Problem: KNN by hand and in Python**

In [15]:
table_dict = {'x1' : [0, 2, 0 , 0, -1, 1],
              'x2' : [3, 0, 1, 1, 0, 1], 
              'x3' : [0, 0, 3, 2, 1, 1], 
              'y' : ['r', 'r', 'r', 'g', 'g', 'r']}

In [16]:
knn_df = pd.DataFrame(data = table_dict)
knn_df

x1  x2  x3  y
0   0   3   0  r
1   2   0   0  r
2   0   1   3  r
3   0   1   2  g
4  -1   0   1  g
5   1   1   1  r

**(a)**

In [17]:
# applying Euclidean formula
knn_df['e_dist'] = np.sqrt(knn_df['x1']**2 + knn_df['x2']**2 + knn_df['x3']**2)
knn_df

x1  x2  x3  y    e_dist
0   0   3   0  r  3.000000
1   2   0   0  r  2.000000
2   0   1   3  r  3.162278
3   0   1   2  g  2.236068
4  -1   0   1  g  1.414214
5   1   1   1  r  1.732051

In [18]:
knn_df['e_dist']

0    3.000000
1    2.000000
2    3.162278
3    2.236068
4    1.414214
5    1.732051
Name: e_dist, dtype: float64

**(b)**

In [19]:
knn_df.loc[:,'y':'e_dist']

y    e_dist
0  r  3.000000
1  r  2.000000
2  r  3.162278
3  g  2.236068
4  g  1.414214
5  r  1.732051

At k = 1, we will take into account a single nearest neighbour to the point 0, 0, 0. **Since the euclidean distance is shortest to Observation 5 (row index 4, 1.414214)**, we predict Y to be **green**.

**(c)**

At k = 3, we will take into account the three nearest neighbours to the point 0, 0, 0. **Since the euclidean distance is shortest to Observation 5 (row index 4, 1.414214, y = g), Observation 6 (row index 5, 1.732051, y = r), and Observation 2, 2.000000, y = r), we predict Y to be red**, based on the mode of the 3 neighbours' observations on Y.

**(d)**

If the Bayes decision boundary is highly non-linear, a **smaller value of K would be better**, as it better fits a non-linear decision boundary that has high variance but lower bias. As K gets larger, the pattern produced will become more linear. 

**(e)**

In [20]:
y = knn_df['y']
x = np.column_stack((knn_df['x1'], knn_df['x2'], knn_df['x3']))
knn_classifier = sk.neighbors.KNeighborsClassifier(n_neighbors=2)
results3 = knn_classifier.fit(x, y)
print(results3.predict([(1, 1, 1)]))

['g']


The KNN classifier of the test point is **green**.

### Problem (3) 
**Multivariable logistic (logit) regression**

In [21]:
auto_df2 = auto_df.iloc[:, 0:10]
mpg_median = auto_df2['mpg'].median()
# create binary variable
auto_df2['mpg_high'] = auto_df2['mpg'].apply(lambda x: 1 if x >= mpg_median else 0)
mpg_median

23.0

In [22]:
auto_df2.head(20)

mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0   18.0          8         307.0       130.0    3504          12.0    70   
1   15.0          8         350.0       165.0    3693          11.5    70   
2   18.0          8         318.0       150.0    3436          11.0    70   
3   16.0          8         304.0       150.0    3433          12.0    70   
4   17.0          8         302.0       140.0    3449          10.5    70   
5   15.0          8         429.0       198.0    4341          10.0    70   
6   14.0          8         454.0       220.0    4354           9.0    70   
7   14.0          8         440.0       215.0    4312           8.5    70   
8   14.0          8         455.0       225.0    4425          10.0    70   
9   15.0          8         390.0       190.0    3850           8.5    70   
10  15.0          8         383.0       170.0    3563          10.0    70   
11  14.0          8         340.0       160.0    3609           8.0    70   
12  15.0          8         400.0       150.0    3761           9.5    70   
13  14.0          8         455.0       225.0    3086          10.0    70   
14  24.0          4         113.0        95.0    2372          15.0    70   
15  22.0          6         198.0        95.0    2833          15.5    70   
16  18.0          6         199.0        97.0    2774          15.5    70   
17  21.0          6         200.0        85.0    2587          16.0    70   
18  27.0          4          97.0        88.0    2130          14.5    70   
19  26.0          4          97.0        46.0    1835          20.5    70   

    origin                          name  const  mpg_high  
0        1     chevrolet chevelle malibu      1         0  
1        1             buick skylark 320      1         0  
2        1            plymouth satellite      1         0  
3        1                 amc rebel sst      1         0  
4        1                   ford torino      1         0  
5        1              ford galaxie 500      1         0  
6        1              chevrolet impala      1         0  
7        1             plymouth fury iii      1         0  
8        1              pontiac catalina      1         0  
9        1            amc ambassador dpl      1         0  
10       1           dodge challenger se      1         0  
11       1            plymouth 'cuda 340      1         0  
12       1         chevrolet monte carlo      1         0  
13       1       buick estate wagon (sw)      1         0  
14       3         toyota corona mark ii      1         1  
15       1               plymouth duster      1         0  
16       1                    amc hornet      1         0  
17       1                 ford maverick      1         0  
18       3                  datsun pl510      1         1  
19       2  volkswagen 1131 deluxe sedan      1         1

**(a)**

In [23]:
LogitModel = sm.Logit(auto_df2['mpg_high'], auto_df2[['const', 'cylinders', 'displacement', 'horsepower', 'weight', 
                                       'acceleration', 'year', 'origin']], missing = 'drop')
# to fix error where 'scipy.stats does not have module chisqprob'
scipy.stats.chisqprob = lambda chisq, df: scipy.stats.chi2.sf(chisq, df)
results4 = LogitModel.fit()
print(results4.summary())

Optimization terminated successfully.
         Current function value: 0.200944
         Iterations 9
                           Logit Regression Results                           
Dep. Variable:               mpg_high   No. Observations:                  392
Model:                          Logit   Df Residuals:                      384
Method:                           MLE   Df Model:                            7
Date:                Fri, 02 Feb 2018   Pseudo R-squ.:                  0.7101
Time:                        00:47:11   Log-Likelihood:                -78.770
converged:                       True   LL-Null:                       -271.71
                                        LLR p-value:                 2.531e-79
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
const          -17.1549      5.764     -2.976      0.003     -28.452      -5.858
cylinders       -0.1626

Both the **weight** and **year** coefficients are statistically significant at the 5% level.

**(b)**

In [24]:
auto_df2 = auto_df2.dropna(axis = 0, how = 'any')
np_x = np.column_stack((auto_df2['const'], auto_df2['cylinders'], auto_df2['displacement'], auto_df2['horsepower'], auto_df2['weight'], 
                     auto_df2['acceleration'], auto_df2['year'], auto_df2['origin']))
X_train, X_test, y_train, y_test = train_test_split(np_x, auto_df2['mpg_high'], test_size = .5,
                                                    random_state=10)

**(c)**

In [25]:
LogReg = LogisticRegression()
results5 = LogReg.fit(X_train, y_train)

In [26]:
results5.coef_

array([[-0.03144305, -0.32570882,  0.00034643, -0.05238895, -0.00491359,
        -0.18112262,  0.30945703, -0.09264595]])

My estimated intercept is **-0.03144305**, and the coefficients are **-0.32570882, 0.00034643, -0.05238895, -0.00491359, -0.18112262, 0.30945703, and -0.09264595** respectively.

**(d)**

In [27]:
y_pred = LogReg.predict(X_test)
confusion_matrix = confusion_matrix(y_test, y_pred)
confusion_matrix

array([[86, 13],
       [12, 85]], dtype=int64)

In [28]:
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          0       0.88      0.87      0.87        99
          1       0.87      0.88      0.87        97

avg / total       0.87      0.87      0.87       196



Given the reported precision, the model predicts both mpg_high and mpg_low relatively **equally well**.